[package]
name = "basic_usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true, features = ["default", "time", "rt", "rt-multi-thread", "sync", "macros"] }
serde_json = "1.0"

hex = "0.4.3"

core = { path = "../../core" }
commons = { path = "../../commons" }

[dependencies.libp2p]
version = "0.44"
features = [
	"identify",
	"kad",
	"mplex",
	"noise",
	"ping",
	"serde",
	"tcp-tokio",
]

[workspace]