[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["default", "time", "rt", "rt-multi-thread", "sync", "macros"] }
config = { version = "0.13.2", features = ["toml"] }
serde = "^1.0"
serde_json = "1.0"
tempdir = "0.3"
futures = "0.3.24"
env_logger = "0.9"
log = "0.4"
async-trait = "0.1.56"
hex = "0.4.3"

# CLI
dialoguer = "0.10.2"
console = "0.15.1"
chrono={ version = "0.4", features = ["clock"]}

# API
warp = {version = "0.3.3"}

commons = { path = "../commons" }
message = { path = "../message"}
network = { path = "../network" }
protocol = { path = "../protocol" }
governance = { path = "../governance" }
ledger = { path = "../ledger" }
thiserror = "1.0"
utoipa="*"

[dependencies.libp2p]
version = "0.44"
features = [
	"identify",
	"kad",
	"mplex",
	"noise",
	"ping",
	"serde",
	"tcp-tokio",
]
